# Generated by Django 2.0.4 on 2018-04-28 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('education', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('relation_status', models.CharField(choices=[('single', 'Single'), ('complicated', 'Complicated'), ('seperated', 'Seperated'), ('not_mention', 'Not Shared')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
